# Generated by Django 6.0.7 on 2026-08-08 10:58

from decimal import Decimal

from django.db import migrations


def seed_plans(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")

    Plan.objects.update_or_create(
        code="free",
        defaults={
            "name": "Free",
            "price_monthly": Decimal("0.00"),
            "short_link_limit": 50,
            "webhook_endpoint_limit": 0,
            "analytics_retention_days": 7,
            "is_active": True,
        },
    )
    Plan.objects.update_or_create(
        code="pro",
        defaults={
            "name": "Pro",
            "price_monthly": Decimal("9.99"),
            "short_link_limit": 5000,
            "webhook_endpoint_limit": 10,
            "analytics_retention_days": 365,
            "is_active": True,
        },
    )


def remove_seeded_plans(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")

    Plan.objects.filter(code__in=["free", "pro"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_plans,
            remove_seeded_plans,
        )
    ]
