# Generated by Django 6.0.7 on 2026-08-08 18:17

from django.db import migrations


def backfill_user_subscriptions(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Plan = apps.get_model("billing", "Plan")
    Subscription = apps.get_model("billing", "Subscription")

    free_plan = Plan.objects.get(code="free")

    users_without_subscription = User.objects.filter(subscription__isnull=True)

    Subscription.objects.bulk_create(
        [
            Subscription(user=user, plan=free_plan, status="active")
            for user in users_without_subscription
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_subscription"),
    ]

    operations = [
        migrations.RunPython(
            backfill_user_subscriptions,
            migrations.RunPython.noop,
        )
    ]
