# Generated by Django 6.0.7 on 2026-08-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcustomer',
            name='provider_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
