# Generated by Django 6.0.7 on 2026-08-13 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_billingcustomer_provider_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_subscription_id', models.CharField(max_length=255, unique=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_subscriptions', to='billing.billingcustomer')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_subscriptions', to='billing.subscription')),
            ],
        ),
    ]
