# Generated by Django 6.0.7 on 2026-08-13 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_providersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], max_length=20)),
                ('provider_price_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_prices', to='billing.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'provider'), name='unique_active_price_per_plan_provider')],
            },
        ),
    ]
