WEBHOOK_SECRET_BYTES = 32
WEBHOOK_SECRET_PREFIX = "whsec_"
WEBHOOK_DELIVERY_TIMEOUT_SECONDS = 10
WEBHOOK_RESPONSE_BODY_MAX_LENGTH = 2000
WEBHOOK_MAX_DELIVERY_ATTEMPTS = 3
WEBHOOK_RETRY_DELAYS = {
    1: 60,
    2: 300,
}
