# Generated by Django 6.0.7 on 2026-07-12 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='links.shortlink')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['short_link', '-clicked_at'], name='click_link_time_idx'), models.Index(fields=['clicked_at'], name='click_time_idx')],
            },
        ),
    ]
